### ISSUE TITLE
Allow users to perform Create, Update and Delete through web page.

### ISSUE THREAD

**Issue by ZachariahWeaver** [ZachariahWeaver/AppBreadCRM#5]
Currently the CRUD operations only work via Postman which handles HTTP requests.

**Comment by irfen-mi** [comment]
@ZachariahWeaver i want to contribute on this and wanna make frontend and allow user to CRUD

**Comment by ZachariahWeaver** [comment]
Hey Muhammad, Can I ask a few questions?

How did you find this project?
Are you experienced in Spiring Boot?
What makes you want to get involved with this project?

Bread CRM is mainly just been for me to learn Spring boot and full stack
development with a deeper understanding. Im open to collaborate but would
want to know a little more about you before accepting a pull request.

Thanks,
Ziggy

**Comment by ZachariahWeaver** [comment]
This has been 95% complete and should be finished by tomorrow morning in next commit. Therefore marking as closed
